### ISSUE TITLE
Create route to stream webcam video

### ISSUE THREAD

**Issue by srishti-negi** [dscigdtuw/photo_effect#3]
Create a separate route called /video_feed which streams webcam video, add this link to nav bar

- In the app directory create an effects.py file
- In effects.py :
    - create a class called effects_lib
        - in this class create a constructor  
        - destructor for video capture and release  
        - a function called get_frame() to read the frame and return it in the form of jpeg to bytes.
- import this class into routes.py and set up a route called /video_feed which streams the webcam video

**Comment by jaassmine** [comment]
Assign this issue to me..
